### ISSUE TITLE
Комментарий от ментора

### ISSUE THREAD

**Issue by mdwebppua** [shadow-doct0r/shadow-doct0r.github.io#1]
**Визуально** - все отлично.

**Размещение файлов** - все отлично.

**Разметка html кода файла index.html:** 
*Структура и расположения тегов хорошо.* 

**Файл стилей css:**
`.cv` не нужно было задавать параметр height: 690px; так как если текста будет больше, документ не потянется или задать параметр min-height, но зачем лишний скрол.

**Comment by shadow-doct0r** [comment]
удалил лишний параметр. закомитил.

**Comment by mdwebppua** [comment]
**ЗАЧЕТ**
